version: '2'
services:
  webclient:
    build: "./webclient/docker"
    ports:
      - "80:80"
    networks:
      - frontend
    restart: on-failure
    depends_on:
      - "webserver"
    environment:
      - API_FQDN=${API_FQDN}
  webserver:
    build: "./webserver/docker"
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    restart: on-failure
    depends_on:
      - "database"
    environment:
      - DBHOST=database
      - DBUSER=${DB_USER}
      - DBPASSWD=${DB_PASSWORD}
  database:
    build: "./mariadb/docker"
    environment:
      - MYSQL_DATABASE=tournament
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - backend
    volumes:
      - "mydata:/var/lib/mysql"
      - "./mariadb/docker/sql:/docker-entrypoint-initdb.d/:Z"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mydata:
