parameters:
  database_host: <<dbhost>>
  database_port: 3306
  database_name: tournament
  database_user: <<dbuser>>
  database_password: <<dbpassword>>
  secret: <<secret>>
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: test@org.org
  mailer_password: null
